import React from 'react';
import { Image, StyleSheet, Text, View } from '@react-pdf/renderer';
import type { Company } from '@/types';

const styles = StyleSheet.create({
  headerWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 0.7,
    borderBottomColor: '#E0DCCD',
  },
  brandLeft: { flexDirection: 'row', alignItems: 'flex-start', flex: 1 },
  logoBox: { width: 56, height: 56, marginRight: 12 },
  logoImg: { width: 56, height: 56, objectFit: 'contain' },
  brandName: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: '#0B0B0B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  contactLine: { fontSize: 8.5, color: '#555', marginTop: 2 },
  websiteLine: { fontSize: 8.5, color: '#F15A24', marginTop: 1 },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 36,
    right: 36,
    paddingTop: 8,
    borderTopWidth: 0.5,
    borderTopColor: '#E0DCCD',
    textAlign: 'center',
  },
  footerTagline: {
    fontSize: 9,
    fontFamily: 'Helvetica-Oblique',
    color: '#F15A24',
    marginBottom: 2,
  },
  footerCredit: { fontSize: 7.5, color: '#999' },
});

interface BrandedHeaderProps {
  company: Pick<
    Company,
    'name' | 'logo_url' | 'address' | 'city' | 'state' | 'zip' | 'phone' | 'email' | 'website'
  >;
  /** Optional right-side block (document title, date, etc.). */
  right?: React.ReactNode;
}

function formatCityStateZip(city?: string | null, state?: string | null, zip?: string | null) {
  const cs = [city, state].filter(Boolean).join(', ');
  return [cs, zip].filter(Boolean).join(' ').trim();
}

function stripUrl(url?: string | null) {
  if (!url) return '';
  return url.replace(/^https?:\/\//i, '').replace(/\/$/, '');
}

export function CompanyHeader({ company, right }: BrandedHeaderProps) {
  const cityStateZip = formatCityStateZip(company.city, company.state, company.zip);
  const phoneEmail = [company.phone, company.email].filter(Boolean).join('  •  ');

  return (
    <View style={styles.headerWrap}>
      <View style={styles.brandLeft}>
        {company.logo_url ? (
          <View style={styles.logoBox}>
            <Image src={company.logo_url} style={styles.logoImg} />
          </View>
        ) : null}
        <View style={{ flexShrink: 1 }}>
          <Text style={styles.brandName}>{company.name}</Text>
          {company.address && (
            <Text style={styles.contactLine}>{company.address}</Text>
          )}
          {cityStateZip && (
            <Text style={styles.contactLine}>{cityStateZip}</Text>
          )}
          {phoneEmail && (
            <Text style={styles.contactLine}>{phoneEmail}</Text>
          )}
          {company.website && (
            <Text style={styles.websiteLine}>{stripUrl(company.website)}</Text>
          )}
        </View>
      </View>
      {right && <View>{right}</View>}
    </View>
  );
}

interface BrandedFooterProps {
  company: Pick<Company, 'tagline' | 'name'>;
}

export function CompanyFooter({ company }: BrandedFooterProps) {
  return (
    <View style={styles.footer} fixed>
      {company.tagline && (
        <Text style={styles.footerTagline}>&ldquo;{company.tagline}&rdquo;</Text>
      )}
      <Text style={styles.footerCredit}>
        Generated by the TLC Management Platform · Powered by Watt Systems
      </Text>
    </View>
  );
}
