-- Migration 045: skill-based crew assignment for the VROOM route optimizer.
--
-- Implements VROOM's native "skills" feature (already supported by the ORS
-- optimization endpoint we proxy). Semantics — a LOCK, not a magnet:
--   * A skill required on a JOB locks it: only crews holding the matching
--     skill may be assigned to it.
--   * A skill granted to a CREW is the key: it makes the crew ELIGIBLE; it does
--     not force them onto those jobs or off others.
-- VROOM keys off small non-negative integers, so each service carries a stable
-- integer `skill_id` that is assigned once and NEVER renumbered.
--
-- Only RESTRICTED services impose a skill on their jobs; unrestricted services
-- contribute no skill and stay doable by any crew, so dispatchers only ever
-- configure the few services that actually need gating.
--
-- Idempotent. Apply to prod manually (same as 043 / 044).

-- 1. Stable VROOM skill key on each service. Identity backfills existing rows
--    with stable values and auto-assigns new ones; the value is never reused or
--    renumbered. Unique so it's safe to use directly as a VROOM skill integer.
alter table services
  add column if not exists skill_id integer generated by default as identity;

create unique index if not exists idx_services_skill_id on services (skill_id);

-- 2. Gate flag. Only restricted services require certification on their jobs.
alter table services
  add column if not exists restricted boolean not null default false;

-- 3. crew_skills — which restricted services each crew is certified for.
create table if not exists crew_skills (
  id uuid primary key default gen_random_uuid(),
  crew_id uuid not null references crews(id) on delete cascade,
  service_id uuid not null references services(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (crew_id, service_id)
);

create index if not exists idx_crew_skills_crew on crew_skills (crew_id);
create index if not exists idx_crew_skills_service on crew_skills (service_id);

alter table crew_skills enable row level security;

-- Company-scoped via the parent crew. Single "for all" policy covers
-- select/insert/delete so the crew certification checklist round-trips.
drop policy if exists "Company members manage crew_skills" on crew_skills;
create policy "Company members manage crew_skills"
  on crew_skills for all
  using (
    crew_id in (
      select id from crews
       where company_id in (select company_id from profiles where id = auth.uid())
    )
  )
  with check (
    crew_id in (
      select id from crews
       where company_id in (select company_id from profiles where id = auth.uid())
    )
  );
